server_name: nanolink-queue
listen: 0.0.0.0:4222
http: 127.0.0.1:8222
max_payload: 64KB
max_connections: 256

jetstream {
  store_dir: /data
  max_memory_store: 16MB
  max_file_store: 512MB
}

authorization {
  user: $NATS_USER
  password: $NATS_PASSWORD
}
